### ISSUE TITLE
CardCharge Exception

### ISSUE THREAD

**Issue by azeez010** [Flutterwave/Python#98]
I have tried all I could but it throws an exception without specifying what to fix.
Why can't this library just generate a payment link? See this error, it;'s very vague "Your card charge call failed with message: An error occured while attempting to decrypt some parameter" How is this supposed to be helpful, I am very frustrated and angry rn. Which parameter is it trying to decrypt? is it my fault? is it the test cards? I don't know, somebody pls help.

**Comment by azeez010** [comment]
No help on this anywhere like this problem doesn't exist, even after copying the payment flow on the docs to replicate the possible success, Infact I will prefer to just generate payment link like stripe and paypal does instead of processing the payments myself. But this library doesn't seems to do that.

**Comment by azeez010** [comment]
Bugs are just everywhere on the platform, tried using flutterwave standard, Its returning "str.replace is not a function" imagine. tried ravepay.co, I am just tried at this point

**Comment by spaceofmiah** [comment]
Hello @azeez010, how are you making your request ?
Can you drop the code snippet.

I was having similar issue `str.replace is not a function` , which i just resolved.

**Comment by spaceofmiah** [comment]
So here is how I was able to get past this error:

First off, I checked this library documentation, i couldn't find anywhere it was documented to generate payment link ( i must've missed it or it's not included yet ), so my implementation was solely through [`httpx`](https://www.python-httpx.org/)  library ( [`requests`](https://pypi.org/project/requests/) library can also work in this case or any other http client library ).


```python
    request_headers = {
        'Authorization': f'Bearer {SK}',
        'Content-Type': 'application/json'               # <--- without this i got str.replace is not a function error
    }

    data = json.dumps({                              # <- without this json.dumps() i got server error from flutterwave
        "redirect_url": "https://your-redirect-url",
        "tx_ref": transaction_ref,
        "customer": customer,
        "amount": amount,
    })
```

[Flutterwave Docs Ref](https://developer.flutterwave.com/docs/collecting-payments/standard/)

**Comment by Corvus97** [comment]
Hello @azeez010 

Thank you for sharing how you resolved this. We definitely would look into improving the error messaging so the corrective steps are intuitive.

@spaceofmiah Thank you for helping out with the issue.
